/**
 * s9 Sc 6 — the hook that runs between packing and signing, and why that is
 * the only moment either of these two jobs can be done.
 *
 * FUSES ARE BYTES IN THE BINARY. `@electron/fuses` finds a sentinel in the
 * Electron executable and rewrites the flags that follow it. Do that after
 * signing and the signature no longer matches the file it covers, so the app
 * refuses to launch with a code-signature error that says nothing about
 * fuses. Do it before packing and there is no binary yet. electron-builder's
 * `afterPack` is exactly the gap between the two, which is why this file
 * exists at all rather than being a step in `pack.mjs`.
 *
 * The licence files have the same timing constraint for a duller reason: they
 * are `extraResources` that are GENERATED, not committed, so they cannot be
 * declared in `electron-builder.yml`'s `extraResources` list without a
 * committed placeholder that would go stale. Writing them here puts them
 * inside the bundle before the signature covers it.
 *
 * `require` and `module.exports`: this file is loaded by electron-builder,
 * which loads hooks with `require`. The package is `"type": "module"`, so the
 * extension has to be `.cjs` or the loader sees ESM syntax in a CJS context.
 */
const {
  existsSync,
  mkdirSync,
  copyFileSync,
  writeFileSync,
} = require('node:fs');
const { dirname, join } = require('node:path');

/**
 * F-126, restated as data so the list in the config and the list in the test
 * are the same seven names in the same order.
 *
 * `RunAsNode` is ON, which is unusual and deliberate: it is what lets
 * `ELECTRON_RUN_AS_NODE=1 WeMessage.app/Contents/MacOS/WeMessage daemon/main.mjs`
 * work at all, and that one property is the whole of F-121 (one Mach-O, one
 * signature, one Team ID, one notarization surface, one TCC identity). The
 * two fuses that make `RunAsNode` dangerous are the ones turned OFF beside
 * it: without `EnableNodeOptionsEnvironmentVariable` nobody can inject code
 * through `NODE_OPTIONS`, and without `EnableNodeCliInspectArguments` nobody
 * can attach a debugger to a process holding Full Disk Access.
 */
const FUSES = {
  RunAsNode: true,
  EnableNodeOptionsEnvironmentVariable: false,
  EnableNodeCliInspectArguments: false,
  EnableCookieEncryption: true,
  EnableEmbeddedAsarIntegrityValidation: true,
  OnlyLoadAppFromAsar: true,
  GrantFileProtocolExtraPrivileges: false,
};

/** Copied verbatim out of the Electron distribution we actually shipped. */
const ELECTRON_LICENCES = [
  ['LICENSE', 'LICENSE.electron.txt'],
  ['LICENSES.chromium.html', 'LICENSES.chromium.html'],
];

exports.default = async function afterPack(context) {
  const { flipFuses, FuseVersion, FuseV1Options } =
    await import('@electron/fuses');

  const appName = `${context.packager.appInfo.productFilename}.app`;
  const app = join(context.appOutDir, appName);

  const wire = { version: FuseVersion.V1, resetAdHocDarwinSignature: false };
  for (const [name, value] of Object.entries(FUSES)) {
    const key = FuseV1Options[name];
    if (key === undefined) {
      throw new Error(`after-pack: @electron/fuses has no fuse named ${name}`);
    }
    wire[key] = value;
  }
  await flipFuses(app, wire);

  // The licence directory is declared in `electron-builder.yml` so that the
  // pack fails loudly if it is missing rather than silently shipping without
  // it; this fills it with the real thing.
  const licences = join(app, 'Contents', 'Resources', 'licenses');
  mkdirSync(licences, { recursive: true });

  const electronDist = dirname(
    require.resolve('electron/package.json', {
      paths: [context.packager.info.appDir],
    }),
  );
  for (const [from, to] of ELECTRON_LICENCES) {
    const src = join(electronDist, 'dist', from);
    if (!existsSync(src)) {
      throw new Error(`after-pack: electron did not ship ${from} at ${src}`);
    }
    copyFileSync(src, join(licences, to));
  }

  // PLACEHOLDER. Sc 11's generator replaces this with the real notices, and
  // the placeholder text is deliberately the kind of sentence nobody would
  // ship: a silent empty file would pass Sc 6 row 3 forever.
  const notices = join(licences, 'THIRD_PARTY_NOTICES.md');
  if (!existsSync(notices)) {
    writeFileSync(
      notices,
      '# Third-party notices\n\n' +
        'PLACEHOLDER — generated by `pnpm licenses:notices` (s9 Sc 11).\n' +
        'A build that ships this file has not run the generator.\n',
    );
  }
};
